<?php
/**
 * Created by PhpStorm.
 * User: CoolCats
 * Date: 2019/3/29
 * Time: 16:50
 */

include_once 'dbconfig.php';
include_once 'Server.php';//引入Server.php
session_start();

class UserServer extends Server
{
    protected $tb_user = "qq_user";//用户账户数据表
    protected $tb_userdetail = "user_detail";//用户详细信息表
    protected $tb_friendship = "qq_friendships";//好友关系表
    protected $tb_messages = "qq_messages";//消息表
    protected $tb_posts = "qq_posts";//post

    public function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    /**
     * 处理注册逻辑
     */
    private function onRegister()
    {
        $query1 = "insert into " . $this->tb_user . " (username," . '"password")' . " values($1,md5($2))";
        $query2 = "insert into " . $this->tb_userdetail
            . " (realname," . 'gender,email,mobile,industry)'
            . " values($1,$2,$3,$4,$5)";

        $params = $this->_requests->params;
        $username = $params->username;
        $password = $params->password;
        $realname = $params->realname;
        $gender = $params->gender;
        $email = $params->email;
        $mobile = $params->mobile;
        $industry = $params->industry;
        $this->_pgsql->queryParams($query1, array(
            $username, $password
        ));
        $this->_pgsql->queryParams($query2, array(
            $realname, $gender, $email, $mobile, $industry
        ));
        $this->makeResponse(true, "注册成功！", NULL);
    }


    /**
     * 主例程
     */
    public function run()
    {
        //登录逻辑
        switch ($this->_requests->type) {
            case "USER_LOGIN":
                $this->onLogin();
                break;
            case "USER_REGISTER":
                //检查用户输入
                $isValid = $this->checkInput();
                if ($isValid) {
                    $this->onRegister();
                } else {
                    $this->makeResponse(false, "注册失败，请检查您的输入！", array());
                    echo $this->_response;//对注册失败进行响应
                }

        }
    }

    /**
     * 处理登录逻辑, 若用户登录信息正确，则成功登录，否则给出错误提示
     */
    private function onLogin()
    {
        $tb_name = "qq_user";
        //构造SQL语句查询用户是否存在，密码采用md5散列存储
        $query = "select count(1) from " . $tb_name . " where username=$1 and " . '"password"=md5($2)';
        $params = $this->_requests->params;
        $loginarr = array(
            $params->username, $params->password
        );
        $this->_pgsql->queryParams($query, $loginarr);
        $row = $this->_pgsql->fetchRow();
        if ($row[0] == 1) {//存在用户

            $_SESSION["user"] = $params->username;//设置session
            $id= $this->getUserId($params->username);
            $friends = $this->getFriendLists($params->username);
            $profile = $this->getUserProfiles($id[0]);
            array_push($profile,$params->username);
            $this->makeResponse(true, "LOGIN SUCCESS", array($friends, $profile));
            echo $this->_response;//对登录成功进行响应
            // show friends lists
        } else {//不存在此用户
            $this->makeResponse(false, "LOGIN FAILURE", NULL);
            echo $this->_response;//对登录失败进行响应

        }
    }

    /**
     * 获取用户简介
     * @param $username
     * @return mixed
     */
    private function getUserProfiles($id)
    {
        $query = "select mobile,email,industry,profession from user_detail" . " where ". '"id"'."=$1";
        $farr = array($id["id"]);
//        var_dump($query);
//        var_dump($id);
//
//        var_dump($farr);
        $this->_pgsql->queryParams($query, $farr);
        $row = $this->_pgsql->fetchRow();
//        var_dump($row);


        return $row;
    }

    private function getUserId($username){
        $query = "select id from qq_user" . " where username=$1";
        $farr = array($username);
        $this->_pgsql->queryParams($query, $farr);
        $row = $this->_pgsql->fetchAll();

        return $row;
    }
    /**
     * @param $user1
     * @return mixed
     */
    private function getFriendLists($user1)
    {
        $query = "select user2 from qq_friendships" . " where user1=$1";
//        $params = $this->_requests->params;
        $farr = array($user1);
        $this->_pgsql->queryParams($query, $farr);
        $row = $this->_pgsql->fetchAll();
        return $row;
    }

    /**
     * 检查用户输入
     * @return bool
     */
    private
    function checkInput()
    {
        return true;
    }
}