<?php
/**
 * Created by PhpStorm.
 * User: CoolCats
 * Date: 2019/3/29
 * Time: 16:50
 */

include_once 'dbconfig.php';
include_once 'Server.php';//引入Server.php

class UserServer extends Server
{
    public function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    /**
     * 处理注册逻辑
     */
    private function onRegister()
    {
        $query1 = "insert into " . $this->tb_user . " (username," . '"password")' . " values($1,md5($2))";
        $query2 = "insert into " . $this->tb_userdetail
            . " (realname," . '"gender",email,mobile,industry)'
            . " values($1,$2,$3,$4,$5)";

        $params = $this->_requests->params;
        $username = $params->username;
        $password = $params->password;
        $realname = $params->realname;
        $gender = $params->gender;
        $email = $params->email;
        $mobile = $params["mobile"];
        $industry = $params["industry"];

//        var_dump($params);

        $this->_pgsql->queryParams($query1, array(
            $username, $password
        ));
//        $row = $this->_pgsql->_querycount;
//        var_dump($row);
//        echo $this->debugTips(0,"语句1影响行数："+$row);
        $this->_pgsql->queryParams($query2, array(
            $realname, $gender, $email, $mobile, $industry
        ));
        $this->makeResponse(true, "注册成功！", NULL);
//        $affected_row = $this->_pgsql->affectedRows();
//        echo $this->debugTips(0,"语句2影响行数："+$affected_row);

    }

    /**
     * 处理登录逻辑, 若用户登录信息正确，则成功登录，否则给出错误提示
     */
    private function onLogin()
    {
        $tb_name = "qq_user";
        //构造SQL语句查询用户是否存在，密码采用md5散列存储
        $query = "select count(1) from " . $tb_name . " where username=$1 and " . '"password"=md5($2)';
        $params = $this->_requests->params;
        $loginarr = array(
            $params->username, $params->password
        );
        $this->_pgsql->queryParams($query, $loginarr);
        $row = $this->_pgsql->fetchRow();
        if ($row[0] == 1) {//存在用户
            $this->makeResponse(true, "LOGIN SUCCESS", array());
            echo $this->_response;//对登录成功进行响应
        } else {//不存在此用户
            $this->makeResponse(false, "LOGIN FAILURE", NULL);
            echo $this->_response;//对登录失败进行响应

        }
    }
    /**
     * 主例程
     */
    public function run()
    {
        //登录逻辑
        switch ($this->_requests->type) {
            case "USER_LOGIN":
                $this->onLogin();
                break;
            case "USER_REGISTER":
                //检查用户输入
                $isValid = $this->checkInput();
                if ($isValid) {
                    //初始化数据库对象
                    $this->_pgsql = new PgSQL();
                    //连接数据库
                    $this->_pgsql->connect();
                    //注册逻辑——判断用户是否存在及密码是否匹配
                    $this->onRegister();
                } else {
                    $this->makeResponse(false, "注册失败，请检查您的输入！", array());
                    echo $this->_response;//对注册失败进行响应
                }

        }
    }

    /**
     * 检查用户输入
     * @return bool
     */
    private function checkInput()
    {
        return true;
    }
}